import { Container } from "react-bootstrap";
import "./App.css";
import Card from "./Card";
import { useState } from "react";

function App() {
  const people = [
    { name: "Nikhil Devarakonda", favoriteColor: "red", favoriteFood: "Mandi" },
    {
      name: "Chaitanya Alwal",
      favoriteColor: "black",
      favoriteFood: "ice-cream",
    },
    {
      name: "Varun Reddy Karra",
      favoriteColor: "blue",
      favoriteFood: "Biryani",
    },
    {
      name: "Mehak Seth",
      favoriteColor: "sky blue",
      favoriteFood: "Naan",
    },
  ];
  const [peopleData, setPeopleData] = useState(people);
  const [formActive, setFormActive] = useState("");
  const [personForm, setPersonForm] = useState({
    name: "",
    favoriteColor: "",
    favoriteFood: "",
  });

  const resetPersonForm = () => {
    setPersonForm({
      name: "",
      favoriteColor: "",
      favoriteFood: "",
    });
  };

  const handleCreatePerson = () => {
    if (formActive === "create") {
      if (
        personForm.name === "" ||
        personForm.favoriteColor === "" ||
        personForm.favoriteFood === ""
      ) {
        alert("Please fill all the fields");
        return;
      }
      setPeopleData([personForm, ...peopleData]);
      resetPersonForm();

      setFormActive("");
    } else {
      if (
        personForm.name === "" ||
        personForm.favoriteColor === "" ||
        personForm.favoriteFood === ""
      ) {
        alert("Please fill all the fields");
        return;
      }
      setPeopleData((data) => {
        return data.map((p) => {
          if (p.name === personForm.name) {
            return personForm;
          }
          return p;
        });
      });
      setFormActive("");
    }
  };

  const handleCancel = () => {
    resetPersonForm();
    setFormActive("");
  };

  const handleEditPerson = (person) => {
    console.log(personForm);
    // setPeopleData((data) => {
    //   return data.filter(
    //     (p) =>
    //       p.name !== person.name &&
    //       p.favoriteColor !== person.favoriteColor &&
    //       p.favoriteFood !== person.favoriteFood
    //   );
    // });
    setFormActive("edit");
    setPersonForm((prev) => {
      return {
        ...prev,
        name: person.name,
        favoriteColor: person.favoriteColor,
        favoriteFood: person.favoriteFood,
      };
    });
    console.log(personForm);
  };
  const handleDeletePerson = (person) => {
    setPeopleData((data) => {
      return data.filter(
        (p) =>
          p.name !== person.name &&
          p.favoriteColor !== person.favoriteColor &&
          p.favoriteFood !== person.favoriteFood
      );
    });
  };
  return (
    <div className="home">
      <div className="py-4 d-flex flex-column align-items-center">
        <div className="w-50 px-4 text-center d-flex justify-content-between align-items-center ">
          <h1 className="text-white bg-dark bg-opacity-75  p-1 rounded-4">
            My Classmates
          </h1>
          <h4
            onClick={() => {
              setFormActive("create");
            }}
            className="text-white bg-dark bg-opacity-75 pointer  p-1 rounded-4"
          >
            + Create
          </h4>
        </div>

        <Container className="w-50 d-flex flex-column gap-3">
          {formActive && (
            // This form is generated by CoPilot
            <div className="bg-secondary text-white fs-4 p-4 rounded-4 w-auto d-flex flex-column gap-3">
              <input
                placeholder="Name"
                className="p-1 rounded-4 w-50 m-auto"
                value={personForm.name}
                onChange={(e) => {
                  setPersonForm({ ...personForm, name: e.target.value });
                }}
                type="text"
              ></input>
              <input
                placeholder="Favorite Color"
                className="p-1 rounded-4 w-50 m-auto"
                value={personForm.favoriteColor}
                onChange={(e) => {
                  setPersonForm({
                    ...personForm,
                    favoriteColor: e.target.value,
                  });
                }}
                type="text"
              ></input>
              <input
                placeholder="Favorite Food"
                className="p-1 rounded-4 w-50 m-auto"
                value={personForm.favoriteFood}
                onChange={(e) => {
                  setPersonForm({
                    ...personForm,
                    favoriteFood: e.target.value,
                  });
                }}
                type="text"
              ></input>
              <div className="w-50 m-auto d-flex justify-content-between">
                <button
                  onClick={handleCreatePerson}
                  className="bg-light text-black px-3 p-1 rounded-pill m-auto"
                >
                  Create
                </button>
                <button
                  onClick={handleCancel}
                  className="bg-light text-black px-3 p-1 rounded-pill m-auto"
                >
                  Cancel
                </button>
              </div>
            </div>
          )}
          {peopleData.map((person, index) => (
            <Card
              key={index}
              person={person}
              handleEditPerson={handleEditPerson}
              handleDeletePerson={handleDeletePerson}
            />
          ))}
        </Container>
      </div>
    </div>
  );
}

export default App;
