import { Container } from "react-bootstrap";
import "./App.css";
import Card from "./Card";
import { useState } from "react";
import DataGridDemo from "./DataGridDemo";
import CreatePerson from "./createPerson";

function App() {
  const people = [
    {
      name: "Nikhil Devarakonda",
      favoriteColor: "red",
      favoriteFood: "Mandi",
      id: 1,
    },
    {
      name: "Chaitanya Alwal",
      favoriteColor: "black",
      favoriteFood: "ice-cream",
      id: 2,
    },
    {
      name: "Varun Reddy Karra",
      favoriteColor: "blue",
      favoriteFood: "Biryani",
      id: 3,
    },
    {
      name: "Mehak Seth",
      favoriteColor: "sky blue",
      favoriteFood: "Naan",
      id: 4,
    },
  ];
  const [peopleData, setPeopleData] = useState(people);
  const [formActive, setFormActive] = useState("");
  const [view, setView] = useState("table");
  const [personForm, setPersonForm] = useState({
    name: "",
    favoriteColor: "",
    favoriteFood: "",
  });

  const resetPersonForm = () => {
    setPersonForm({
      name: "",
      favoriteColor: "",
      favoriteFood: "",
    });
  };

  const handleCreatePerson = () => {
    if (formActive === "create") {
      if (
        personForm.name === "" ||
        personForm.favoriteColor === "" ||
        personForm.favoriteFood === ""
      ) {
        alert("Please fill all the fields");
        return;
      }
      personForm.id = peopleData.length + 1;
      setPeopleData([personForm, ...peopleData]);
      resetPersonForm();

      setFormActive("");
    } else {
      if (
        personForm.name === "" ||
        personForm.favoriteColor === "" ||
        personForm.favoriteFood === ""
      ) {
        alert("Please fill all the fields");
        return;
      }
      setPeopleData((data) => {
        return data.map((p) => {
          if (p.name === personForm.name) {
            return personForm;
          }
          return p;
        });
      });
      setFormActive("");
    }
  };

  const handleCancel = () => {
    resetPersonForm();
    setFormActive("");
  };

  const handleEditPerson = (person) => {
    console.log(personForm);
    // setPeopleData((data) => {
    //   return data.filter(
    //     (p) =>
    //       p.name !== person.name &&
    //       p.favoriteColor !== person.favoriteColor &&
    //       p.favoriteFood !== person.favoriteFood
    //   );
    // });
    setFormActive("edit");
    setPersonForm((prev) => {
      return {
        ...prev,
        name: person.name,
        favoriteColor: person.favoriteColor,
        favoriteFood: person.favoriteFood,
      };
    });
    console.log(personForm);
  };
  const handleDeletePerson = (person) => {
    setPeopleData((data) => {
      return data.filter(
        (p) =>
          p.name !== person.name &&
          p.favoriteColor !== person.favoriteColor &&
          p.favoriteFood !== person.favoriteFood
      );
    });
  };
  return (
    <div className="home">
      <div className="w-100 py-4 d-flex flex-column align-items-center">
        <div className="w-50 px-4 text-center d-flex justify-content-between align-items-center ">
          <h1 className="text-white bg-dark bg-opacity-75  p-1 rounded-4">
            My Classmates
          </h1>
          <h4
            onClick={() => {
              if (view === "tile") {
                setView("table");
              } else {
                setView("tile");
              }
            }}
            className="text-white bg-dark bg-opacity-75 pointer p-1 rounded-4"
          >
            {view === "tile" ? "Table view" : "Tile view"}
          </h4>
          <h4
            onClick={() => {
              if (formActive === "create") {
                setFormActive("");
              } else {
                setFormActive("create");
              }
            }}
            className="text-white bg-dark bg-opacity-75 pointer  p-1 rounded-4"
          >
            {"+ Create Person"}
          </h4>
        </div>

        {formActive && (
          // This form is generated by CoPilot
          <Container className="w-50 p-4">
            <CreatePerson
              handleCancel={handleCancel}
              handleCreatePerson={handleCreatePerson}
              personForm={personForm}
              setPersonForm={setPersonForm}
            />
          </Container>
        )}
        {view === "tile" && (
          <Container className="w-50 d-flex flex-column gap-3">
            {peopleData.map((person, index) => (
              <Card
                key={index}
                person={person}
                handleEditPerson={handleEditPerson}
                handleDeletePerson={handleDeletePerson}
              />
            ))}
          </Container>
        )}
        {view === "table" && <DataGridDemo peopleData={peopleData} />}
      </div>
    </div>
  );
}

export default App;
