const CreatePerson = ({
  personForm,
  setPersonForm,
  handleCreatePerson,
  handleCancel,
  formType,
}) => {
  // This form is generated by CoPilot
  return (
    <div className="w-50 bg-secondary text-white fs-4 p-4 rounded-4 w-auto d-flex flex-column gap-3">
      <input
        placeholder="Name"
        className="p-1 rounded-4 w-50 m-auto"
        value={personForm.name}
        onChange={(e) => {
          setPersonForm({ ...personForm, name: e.target.value });
        }}
        type="text"
      ></input>
      <input
        placeholder="Favorite Color"
        className="p-1 rounded-4 w-50 m-auto"
        value={personForm.favoriteColor}
        onChange={(e) => {
          setPersonForm({
            ...personForm,
            favoriteColor: e.target.value,
          });
        }}
        type="text"
      ></input>
      <input
        placeholder="Favorite Food"
        className="p-1 rounded-4 w-50 m-auto"
        value={personForm.favoriteFood}
        onChange={(e) => {
          setPersonForm({
            ...personForm,
            favoriteFood: e.target.value,
          });
        }}
        type="text"
      ></input>
      <div className="w-50 m-auto d-flex justify-content-between">
        <button
          onClick={handleCreatePerson}
          className="bg-light text-black px-3 p-1 rounded-pill m-auto"
        >
          {formType === "create" ? "Create" : "Update"}
        </button>
        <button
          onClick={handleCancel}
          className="bg-light text-black px-3 p-1 rounded-pill m-auto"
        >
          Cancel
        </button>
      </div>
    </div>
  );
};

export default CreatePerson;
